language: c
dist: trusty
sudo: required

os: 
  - linux
  - osx

env:
   global:
     - CRAN: "http://cran.rstudio.com"
     - R_BUILD_ARGS="--no-build-vignettes --no-manual"
     - R_CHECK_ARGS="--no-build-vignettes --no-manual --no-examples"
     - BOOTSTRAP_LATEX=""
     - NOT_CRAN="true"

script: ./travis-tool.sh run_tests

addons:
  apt:
    packages:
    - gdal-bin 
    - libgdal-dev
    - libgdal1-dev
    - libproj-dev

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh install_deps
  
r_github_packages:
  - jimhester/covr
  
after_success:
  - Rscript -e 'covr::coveralls()'

after_failure:
  ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change